import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import HeaderButtons from '../src/components/HeaderButtons'
import Body from '../src/components/Body'
import Footer from '../src/components/Footer'
import CallUs from '../src/components/CallUs'


const Home: NextPage = () => {
  return (
    <>

      <Head>
        <title>Sydney Cleaners</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderButtons />
      <CallUs />
      <Body />
      <Footer />

    </>
  )
}

export default Home
